<li>
            	<div class="tuan_ico"><span>[field:discount/]</span>折</div>
            	<a class="fl" href="[field:url/]" target="_blank"><img class="fl lazyimg" src="" data-original="[field:lit240/]" width="223" height="163" alt="[field:title/]" title="[field:title/]" /></a>
              <p class="p1"><a href="[field:url/]" target="_blank">[field:title/]</a></p>
              <p class="p2"><span>优惠价：<i>&yen;</i><strong>[field:ourprice/]</strong></span><s>原价：&yen;[field:sellprice/]</s></p>
            </li>