<div class="dz_lidt">
                        <div class="head_pic_left">
                            <img src="[field:litpic/]" width="50" height="50"  title="[field:nickname/]" />
                        </div>
                        <div class="body_con_rig">
                            <div class="lp_ico"></div>
                            <dl>
                                <dt><p class="p1"><span>会员：</span>[field:nickname/]</p><p class="p2">获得点评奖金 &yen;[field:jifencomment/]</p></dt>
                                <dd class="dd_1"><span>客户点评：</span>[field:content/]</dd>
                                <dd class="dd_2">
                                    <p><b>住宿环境：</b><span><s style=" width: [field:percent1/]"></s></span></p>
                                    <p><b>交通位置：</b><span><s style=" width: [field:percent2/]"></s></span></p>
                                    <p><b>卫生情况：</b><span><s style=" width: [field:percent3/]"></s></span></p>
                                    <p><b>性价比：</b><span><s style=" width: [field:percent4/]"></s></span></p>
                                </dd>
                            </dl>
                        </div>
                    </div>