<li [field:global.autoindex runphp='yes']if(@me%5==0)@me='class="mr_0"';else @me='';[/field:global.autoindex]>
                        <a class="fl" href="[field:url/]" target="_blank"><img class="fl lazyimg" src="" data-original="[field:lit240/]" width="180" height="120" alt="[field:title/]" title="[field:title/]" /></a>
                        <p class="p1"><a href="[field:url/]" target="_blank">[field:title/]</a></p>
                        <p class="p2"><span class="sp1"><a href="/raiders/[field:pinyin/]" target="_blank">[field:destname/]</a></span><span class="sp2">[field:shownum/]</span></p>
                        </li>