<li class="txt_img_list">
                            <a class="fl" href="[field:url/]" target="_blank"><img class="fl lazyimg" src="" data-original="[field:lit240/]" width="145" height="100" alt="[field:title/]"  /></a>
                            <p class="tit"><a href="[field:url/]" target="_blank">[field:title/]</a></p>
                            <p class="txt">[field:content function="cutstr_html(strip_tags(@me),100)"/]</p>
                        </li>