<li>
                        <s>优惠</s>
                        <a class="fl" href="[field:url/]" target="_blank"><img src="[field:lit160/]" alt="[field:title/]" title="[field:title/]" /></a>
                      <p class="p1"></p>
                      <p class="p2">&yen;[field:sellprice/]</p>
                      <p class="p3"><a href="[field:url/]" target="_blank">[field:title/]</a></p>
                    </li>