<div class="tall" style="display:none">
                <span class="tit_bt">
                  <s></s>
                  <h3>
                      <a class="title_bt" href="javascript:;">{sline:field.kindname/}</a>
                  </h3>
                </span>
        <div class="gl_nav_con" style="display:none">
            <div class="subitem">
                {sline:getslidenav}
                    <dl>
                        <dt>[field:categoryname/]</dt>
                        <dd>
                            [field:categorychild/]
                        </dd>
                    </dl>
                {/sline:getslidenav}

            </div>
        </div>
    </div>