<dl>
                    <dt><s>抢购</s><a class="fl" href="[field:url/]" target="_blank"><img src="[field:litpic/]" alt="[field:title/]" title="[field:title/]" /></a></dt>
                    <dd class="d1"><a href="[field:url/]" target="_blank">[field:title/]</a></dd>
                    <dd class="d2">[field:sellpoint/]</dd>
                    <dd class="d3"><span>&yen;[field:sellprice/]</span>起</dd>
                  </dl>