<div class="gl_top">
                <a class="fl" href="[field:url/]" target="_blank"><img class="fl"  src="[field:litpic/]" width="368" height="228" alt="[field:title/]" /></a>
                <div class="ct_ico">团购</div>
                <div class="tg"><a class="title" href="[field:title/]">[团购][field:title/]</a><a class="ct_btn" href="/tuan/show_[field:aid/].html">参团</a></div>
            </div>